name: CI

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      #  with:
      #    fetch-depth: 0

      - name:  Install Nix
        uses: cachix/install-nix-action@v14.1
        with:
          install_url: https://releases.nixos.org/nix/nix-2.3.7/install

      - name: Build inside nix-shell
        uses: workflow/nix-shell-action@v2
        with:
          packages: nixos-generators
          script: ./build.sh

